---
- name: "Create directory"
  file:
    path: ~/udapeople
    state: directory

- name: "Extract artifact to EC2"
  unarchive:
    src: ~/project/artifact.tar.gz
    # src: artifact.tar.gz
    dest: ~/udapeople

- name: "install nodejs and npm"
    become: yes
    apt:
      name: ["npm"]
      state: latest
      update_cache: yes

- name: "install pm2"
    become: yes
    npm:
      name: pm2
      global: yes
      production: yes
      state: present

- name: "Install Dependencies and build app"
  shell: |
    cd ~/udapeople
    npm install
  

- name: "Run pm2"
  shell: |
    cd ~/udapeople
    pm2 stop default
    pm2 start npm -- start