---
- name: "Create directory"
  file:
    path: ~/udapeople
    state: directory

- name: "Extract artifact to EC2"
  unarchive:
    src: ~/project/artifact.tar.gz
    # src: artifact.tar.gz
    dest: ~/udapeople

- name: "install npm"
  become: yes
  apt:
    name: ["npm"]
    state: latest
    update_cache: yes

- name: "install n"
  become: yes
  npm:
    name: n
    global: yes
    production: yes

- name: "install nodejs 13.8.0"
  become: yes
  shell: n 13.8.0

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "Install Dependencies and build app"
  shell: |
    cd ~/udapeople
    npm install
  

- name: "Run pm2"
  shell: |
    cd ~/udapeople/dist
    pm2 stop default
    pm2 start main.js
  register: excute

- name: "message"
  debug: 
    msg: "{{excute.stdout_lines}}"

- name: "configure pm2 to start server"
  become: true 
  shell: |
    env PATH=$PATH:usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu  